set termguicolors
" Huginn theme accent overrides (generated by huginn-theme)
let s:huginn_theme = expand('~/.config/huginn/huginn-theme.vim')
if filereadable(s:huginn_theme) | execute 'source ' . s:huginn_theme | endif

set laststatus=2
let g:tokyonight_style = 'night' " available: night, storm
let g:tokyonight_enable_italic = 1
let g:lightline = {'colorscheme' : 'tokyonight'}

colorscheme tokyonight
